global:
  resolve_timeout: 5m
  slack_api_url_file: /etc/alertmanager/secrets/slack-webhook-url

route:
  receiver: null
  group_by:
    - alertname
    - service
    - severity
  group_wait: 30s
  group_interval: 5m
  repeat_interval: 3h
  routes:
    - matchers:
        - notify="ops-slack"
      receiver: ops-slack
      continue: false

receivers:
  - name: null

  - name: ops-slack
    slack_configs:
      - channel: '#ops-alerts'
        send_resolved: true
        title: >-
          [{{ .Status | toUpper }}][{{ .CommonLabels.severity | toUpper }}]
          {{ .CommonLabels.alertname }}
        text: >-
          {{ range .Alerts -}}
          *service:* {{ .Labels.service }}
          *summary:* {{ .Annotations.summary }}
          *description:* {{ .Annotations.description }}
          *runbook:* {{ .Annotations.runbook_url }}
          {{ end }}
