import fs from "node:fs";
import path from "node:path";

import { COMMAND_FAMILY_ORDER, getFamilyUsage, renderFamilyHelp } from "./command-family.ts";

const OUTPUT_PATH = path.resolve("docs", "command-index.md");

export function renderCommandIndexMarkdown(): string {
  const lines: string[] = [
    "# Command Index",
    "",
    "Generated from the unified CLI help output. Do not edit this file by hand; regenerate it with `npm run docs:command-index`.",
    "",
  ];

  for (const family of COMMAND_FAMILY_ORDER) {
    lines.push(`## \`${getFamilyUsage(family)}\``);
    lines.push("");
    lines.push("```text");
    lines.push(renderFamilyHelp(family).trimEnd());
    lines.push("```");
    lines.push("");
  }

  return `${lines.join("\n").trim()}\n`;
}

function main(): void {
  const check = process.argv.slice(2).includes("--check");
  const nextMarkdown = renderCommandIndexMarkdown();

  if (check) {
    const currentMarkdown = fs.existsSync(OUTPUT_PATH) ? fs.readFileSync(OUTPUT_PATH, "utf8") : "";
    if (currentMarkdown !== nextMarkdown) {
      throw new Error(
        `command index is stale. Regenerate ${path.relative(process.cwd(), OUTPUT_PATH).replace(/\\/g, "/")} with \`npm run docs:command-index\`.`,
      );
    }

    console.log(`Command index is up to date: ${path.relative(process.cwd(), OUTPUT_PATH).replace(/\\/g, "/")}`);
    return;
  }

  fs.writeFileSync(OUTPUT_PATH, nextMarkdown, "utf8");
  console.log(`Wrote command index: ${path.relative(process.cwd(), OUTPUT_PATH).replace(/\\/g, "/")}`);
}

if (process.argv[1] && path.resolve(process.argv[1]) === path.resolve(new URL(import.meta.url).pathname)) {
  main();
}

export { OUTPUT_PATH as COMMAND_INDEX_OUTPUT_PATH };
