apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-veil-server
  annotations:
    nginx.ingress.kubernetes.io/proxy-http-version: "1.1"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "3600"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "3600"
spec:
  ingressClassName: nginx
  rules:
    - host: game.projectveil.example
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: project-veil-server
                port:
                  name: http
