apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-veil-server-canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
spec:
  ingressClassName: nginx
  rules:
    - host: game.projectveil.prod
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: project-veil-server-canary
                port:
                  name: http
