apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: project-veil-server-canary
  annotations:
    nginx.ingress.kubernetes.io/canary: "true"
    nginx.ingress.kubernetes.io/canary-weight: "10"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      more_set_headers "Strict-Transport-Security: max-age=31536000; includeSubDomains; preload";
      more_set_headers "Content-Security-Policy: default-src 'self'; connect-src 'self' https://*.sentry.io wss://game.projectveil.prod; img-src 'self' data: https:; script-src 'self'; style-src 'self' 'unsafe-inline'; frame-ancestors 'none'";
      more_set_headers "X-Frame-Options: DENY";
      more_set_headers "X-Content-Type-Options: nosniff";
      more_set_headers "Referrer-Policy: strict-origin-when-cross-origin";
      more_set_headers "Permissions-Policy: camera=(), geolocation=(), microphone=()";
spec:
  ingressClassName: nginx
  rules:
    - host: game.projectveil.prod
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: project-veil-server-canary
                port:
                  name: http
